name: build

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: test_db
        ports:
          - 5444:5432
    steps:
    - uses: actions/checkout@v2
    - run: cargo build
    - run: cargo test

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build 

  # Windows does not have tests ( do not know at the moment how to test postgres )
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build 
